FROM node:15.14.0-alpine3.11

ARG AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_SESSION_TOKEN
ARG NODE_ENV

WORKDIR /home/node/app

COPY . /home/node/app

RUN npm install

CMD npm start
